# Site settings
title: An Iteration
email: 
description: > # this means to ignore newlines until "baseurl:"
  Simple fellow taking a real simple approach to a sometimes challenging problem.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://terrence.benade.com.au" # the base hostname & protocol for your site
twitter_username: terrencebenade
github_username:  tbenade

# Build settings
markdown: kramdown

kramdown:
  input: GFM
